---
 - hosts: lb01
   tasks: 
   - name: "add lb01 record"
     lineinfile: dest=/etc/hosts regexp='^<lb01-ip>' 
                 line="<lb01-ip>\tlb01"
                 state=present

   - name: "add db01 record"
     lineinfile: dest=/etc/hosts regexp='^<lb01-ip>' 
                 line="<db01-ip>\tdb0101"
                 state=present

   - name: "add app01 record"
     lineinfile: dest=/etc/hosts regexp='^<lb01-ip>' 
                 line="<app01-ip>\tapp01"
                 state=present

   - name: "add lapp02 record"
     lineinfile: dest=/etc/hosts regexp='^<lb01-ip>' 
                 line="<app02-ip>\tapp02"
                 state=present

   - name: "add ansible-master record"
     lineinfile: dest=/etc/hosts regexp='^<lb01-ip>' 
                 line="<ansible-master-ip>\tansible-master"
                 state=present

