---
- hosts: webserver
  tasks:
    - name: install web components
      apt: name={{item}} update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: start apache
      service: name=apache2 state=started enabled=yes

    - name: enable wsgi
      apache2_module: state=present name=wsgi
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: name=alache2 state=restarted
